"""add product metadata

Revision ID: 81e44662ad36
Revises: 4e42d83b1f51
Create Date: 2026-09-09 14:09:11.659188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e44662ad36'
down_revision: Union[str, Sequence[str], None] = '4e42d83b1f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sku', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    # Dado que hemos añadido nuevos campos y 'sku' debe ser único y no nulo, necesitamos rellenar los valores 
    # existentes antes de aplicar las restricciones. 
    # Para eso ejecutamos una actualización que genere un SKU basado en el ID del producto.
    op.execute("UPDATE products SET sku = 'PROD-' || LPAD(id::text, 6, '0') WHERE sku IS NULL")

    # Después de rellenar los valores, podemos aplicar las restricciones de no nulo y único.
    # Ya que tenemos los productos con 'sku' rellenado.
    op.alter_column(
        "products",
        "sku",
        existing_type=sa.String(length=50),
        nullable=False,
    )
    # Impedimos que se repitan los valores de 'sku' en la tabla.
    op.create_unique_constraint(
        "uq_products_sku",
        "products",
        ["sku"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_products_sku",
        "products",
        type_="unique",
    )
    op.drop_column('products', 'update_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'active')
    op.drop_column('products', 'sku')
    # ### end Alembic commands ###
